de-CLAW
Islandora-Devops/claw-playbook pull request #234
Opened 2022-10-17 17:02 UTC by seth-shaw-asu

**GitHub Issue**: N/A

# What does this Pull Request do?

Removes references to CLAW and Islandora 8.

# What's new?
Removes references to CLAW and Islandora 8.

# How should this be tested?

Read through and make sure I didn't botch any URLs, etc.

# Additional Notes:

I left the namespaces file `claw.cnd` as I felt it didn't harm anything and I didn't want to miss a reference to it.

# Interested parties
Tag (@ mention) interested parties or, if unsure, @Islandora-Devops/committers

2022-10-19 17:14 UTC, adam-vessey commented on roles/internal/Islandora-Devops.drupal-openseadragon/README.md
> +An Ansible role that installs the [Drupal 8 field formatter](https://github.com/Islandora/openseadragon) and [OpenSeadragon library](https://openseadragon.github.io/) on:
```suggestion
An Ansible role that installs the [Drupal field formatter](https://github.com/Islandora/openseadragon) and [OpenSeadragon library](https://openseadragon.github.io/) on:
```

since we're dealing with D9, and soon 10?

2022-10-19 18:11 UTC, seth-shaw-asu commented on roles/internal/Islandora-Devops.drupal-openseadragon/README.md
> +An Ansible role that installs the [Drupal 8 field formatter](https://github.com/Islandora/openseadragon) and [OpenSeadragon library](https://openseadragon.github.io/) on:
Thanks, I found another reference while I was at it.

2022-10-19 18:15 UTC, whikloj requested changes
The 2 lines referenced should be updated. I also found several other uses of "claw" in the ansible code, but also in 
```
roles/internal/webserver-app/tasks/solr.yml:# Solr server configuration should go into the solr playbook: https://github.com/Islandora-Devops/claw-playbook/blob/dev/solr.yml
```

2022-10-19 18:15 UTC, whikloj commented on forBeginners.md
>  >$ git clone https://github.com/Islandora-Devops/claw-playbook.git
Missed a `claw` here

2022-10-19 18:15 UTC, whikloj commented on forBeginners.md
>  >$ git clone https://github.com/Islandora-Devops/claw-playbook.git
Also on line 95 below, both should be `islandora-playbook`.

2022-10-20 15:40 UTC, seth-shaw-asu commented
Helps to _save_ your open files before doing the `git add`... 🙄

2022-10-21 13:50 UTC, whikloj approved these changes
Looks good and still builds.

2022-10-21 13:50 UTC, merged